version: "3" # composeファイルのバージョン
services: 
  app: # サービス名
    build: ./backend/ # ①ビルドに使うDockerfileの場所
    tty: true # ②コンテナの永続化
    ports: # ホストOSのポートとコンテナのポートをつなげる 
        - "9990"
    volumes:
        - ./backend:/go/src/Spotify_new_releases # ③マウントディレクトリ
    environment:
      - REDIRECT_URI=$REDIRECT_URI
      - SPOTIFY_ID_3=$SPOTIFY_ID_3
      - SPOTIFY_SECRET_3=$SPOTIFY_SECRET_3
      - ERR_URI=$ERR_URI
      - SUC_URI=$SUC_URI
      - LOCAL_ERR_URI=$LOCAL_ERR_URI
      - LOCAL_SUC_URI=$LOCAL_SUC_URI
      - SQL_PATH=$SQL_PATH
      - VIRTUAL_HOST=newlreases.tk
      - LETSENCRYPT_HOST=newlreases.tk
      - LETSENCRYPT_EMAIL=@gmail.com
    depends_on:
        - mysql
    networks: 
      - app1
      # - default
    # network_mode: "bridge"
    command: bash -c "go run main.go"

  mysql:
    build: ./mysql/
    volumes:
        # 初期データを投入するSQLが格納されているdir
        - ./mysql/init:/docker-entrypoint-initdb.d
        # 永続化するときにマウントするdir
        - db-store:/var/lib/mysql
    environment: 
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
        - "3306:3306"
    # network_mode: "bridge"
    networks: 
      - app1

  # nginx:
  #   image: nginx
  #   depends_on:
  #    - app
  #   container_name: app-nginx
  #   environment:
  #     - VIRTUAL_HOST: newlreases.tk
  #     - LETSENCRYPT_HOST: newlreases.tk
  #     - LETSENCRYPT_EMAIL: @gmail.com
  #   restart: always
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   network_mode: "bridge"
    
volumes:
  db-store:

# networks:
#   app1:
#     driver: bridge

# networks:
#   default:
#     external:
#       name: app1

networks: 
  app1:
    external: true

# networks:
#   default:
#    external:
#     name: bridge
#   app_net:
#     name: app1


